# fly.toml file generated for floral-flower-8496 on 2021-04-05T17:52:04+02:00

app = "floral-flower-8496"

kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    port = "8080"
    restart_limit = 6
    timeout = "2s"

[experimental]
private_network = true
